# Generated by Django 5.2.7 on 2025-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('DROPS', 'Drops'), ('POWDER', 'Powder'), ('OINTMENT', 'Ointment'), ('OTHER', 'Other')], default='Other', max_length=50),
        ),
    ]
