# Generated by Django 5.2.7 on 2025-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_total_amount_invoice_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
